# Generated by Django 4.0.4 on 2022-05-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_first_name_contributor_first_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='email',
            new_name='emails',
        ),
    ]
