# Generated by Django 4.0.4 on 2022-05-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_email_contributor_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='emails',
            new_name='email',
        ),
    ]
